[server]
headless = true
port = 8501
enableCORS = false
[browser]
gatherUsageStats = false
[theme]
base = "light"
primaryColor = "#4E6BFE"
[deprecation]
showfileUploaderEncoding = false
[logger]
level = "error"
